//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
)

type unpackIntegerType struct {
	name        string
	fileName    string
	goType      string
	store       string
	valueStride int
	valueShift  int
}

var unpackIntegerTypes = []unpackIntegerType{
	{name: "Int32", fileName: "int32", goType: "int32", store: "MOVL", valueStride: 4, valueShift: 2},
	{name: "Int64", fileName: "int64", goType: "int64", store: "MOVQ", valueStride: 8, valueShift: 3},
}

func main() {
	for _, integerType := range unpackIntegerTypes {
		generateGo(integerType)
		generateAssembly(integerType)
	}
}

func generateGo(integerType unpackIntegerType) {
	var out bytes.Buffer
	f := &out
	maxWidth := integerType.valueStride*8 - 1

	fmt.Fprintln(f, "//go:build !purego && !goexperiment.simd")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by gen_unpack_amd64.go; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package bitpack")
	fmt.Fprintln(f)
	for width := 1; width <= maxWidth; width++ {
		fmt.Fprintln(f, "//go:noescape")
		fmt.Fprintf(f, "func unpack%sx%dbitsAMD64(dst []%s, src []byte)\n\n", integerType.name, width, integerType.goType)
	}
	fmt.Fprintf(f, "func unpack%sGeneratedAMD64(dst []%s, src []byte, bitWidth uint) {\n", integerType.name, integerType.goType)
	fmt.Fprintln(f, "\tswitch bitWidth {")
	for width := 1; width <= maxWidth; width++ {
		fmt.Fprintf(f, "\tcase %d:\n\t\tunpack%sx%dbitsAMD64(dst, src)\n", width, integerType.name, width)
	}
	fmt.Fprintln(f, "\t}")
	fmt.Fprintln(f, "}")

	fileName := fmt.Sprintf("unpack_%s_generated_amd64.go", integerType.fileName)
	if err := os.WriteFile(fileName, out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func generateAssembly(integerType unpackIntegerType) {
	var out bytes.Buffer
	f := &out
	maxWidth := integerType.valueStride*8 - 1

	fmt.Fprintln(f, "//go:build !purego && !goexperiment.simd")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by gen_unpack_amd64.go; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "#include \"textflag.h\"")
	for width := 1; width <= maxWidth; width++ {
		fmt.Fprintln(f)
		emitKernel(f, integerType, width)
	}

	fileName := fmt.Sprintf("unpack_%s_generated_amd64.s", integerType.fileName)
	if err := os.WriteFile(fileName, out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func emitKernel(f io.Writer, integerType unpackIntegerType, width int) {
	fmt.Fprintf(f, "// func unpack%sx%dbitsAMD64(dst []%s, src []byte)\n", integerType.name, width, integerType.goType)
	fmt.Fprintf(f, "TEXT ·unpack%sx%dbitsAMD64(SB), NOSPLIT, $0-48\n", integerType.name, width)
	fmt.Fprintln(f, "\tMOVQ dst_base+0(FP), AX")
	fmt.Fprintln(f, "\tMOVQ dst_len+8(FP), DX")
	fmt.Fprintln(f, "\tMOVQ src_base+24(FP), BX")
	fmt.Fprintf(f, "\tSHLQ $%d, DX\n", integerType.valueShift)
	fmt.Fprintln(f, "\tADDQ AX, DX")
	if width > 32 {
		fmt.Fprintf(f, "\tMOVQ $0x%x, R11\n", uint64(1)<<width-1)
	}
	fmt.Fprintf(f, "unpack_%s_%dbit_amd64_loop:\n", integerType.fileName, width)

	currentWord := -1
	nextWord := -1
	for value := 0; value < 8; value++ {
		bitOffset := value * width
		word := bitOffset / 64
		shift := bitOffset % 64
		crosses := shift+width > 64

		if word != currentWord {
			if word == nextWord {
				fmt.Fprintln(f, "\tMOVQ R9, R8")
			} else {
				fmt.Fprintf(f, "\tMOVQ %d(BX), R8\n", word*8)
			}
			currentWord = word
			nextWord = -1
		}
		if crosses && nextWord != word+1 {
			fmt.Fprintf(f, "\tMOVQ %d(BX), R9\n", (word+1)*8)
			nextWord = word + 1
		}

		fmt.Fprintln(f, "\tMOVQ R8, R10")
		switch {
		case crosses:
			fmt.Fprintf(f, "\tSHRQ $%d, R9, R10\n", shift)
		case shift != 0:
			fmt.Fprintf(f, "\tSHRQ $%d, R10\n", shift)
		}

		switch {
		case width <= 31:
			fmt.Fprintf(f, "\tANDL $0x%x, R10\n", uint32(1)<<width-1)
		case width == 32:
			fmt.Fprintln(f, "\tMOVL R10, R10")
		default:
			fmt.Fprintln(f, "\tANDQ R11, R10")
		}
		fmt.Fprintf(f, "\t%s R10, %d(AX)\n", integerType.store, value*integerType.valueStride)
	}

	fmt.Fprintf(f, "\tADDQ $%d, BX\n", width)
	fmt.Fprintf(f, "\tADDQ $%d, AX\n", 8*integerType.valueStride)
	fmt.Fprintln(f, "\tCMPQ AX, DX")
	fmt.Fprintf(f, "\tJB unpack_%s_%dbit_amd64_loop\n", integerType.fileName, width)
	fmt.Fprintln(f, "\tRET")
}
