//go:build ignore

// gen_unpack_simd_amd64.go generates the shuffle, permutation and shift
// tables used by the simd/archsimd unpacking kernels (see
// unpack_int32_simd_amd64.go and unpack_int64_simd_amd64.go for how each
// table is consumed).
//
// The value at index i of a group of 8 starts at bit i*bitWidth: in byte
// i*bitWidth/8 of the input, offset by i*bitWidth%8 bits. The tables encode,
// per bit width, which input bytes each 32 or 64 bit lane gathers and by how
// much the lane is shifted to align the value.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

type unpackInt32Shuffle struct {
	lo0 [16]int8
	lo1 [16]int8
	hi0 [16]int8
	hi1 [16]int8
	sr0 [4]uint32
	sr1 [4]uint32
	sl0 [4]uint32
	sl1 [4]uint32
}

type unpackInt64Permute struct {
	perm0  [8]uint32
	perm1  [8]uint32
	shift0 [4]uint64
	shift1 [4]uint64
}

type unpackInt64WidePermute struct {
	permLo0 [8]uint32
	permHi0 [8]uint32
	permLo1 [8]uint32
	permHi1 [8]uint32
	sr0     [4]uint64
	sl0     [4]uint64
	sr1     [4]uint64
	sl1     [4]uint64
}

func int32Shuffle(bitWidth uint) unpackInt32Shuffle {
	var m unpackInt32Shuffle
	for i := range 16 {
		m.lo0[i], m.lo1[i], m.hi0[i], m.hi1[i] = -128, -128, -128, -128
	}
	// For bit widths up to 16 all 8 values fit in the first 16 bytes, so
	// lanes 4-7 index src[j:] directly and the kernel performs a single
	// load; wider values straddle the boundary, so lanes 4-7 index a second
	// load at src[j+g:].
	g := uint(0)
	if bitWidth > 16 {
		g = (4 * bitWidth) / 8
	}
	for lane := uint(0); lane < 8; lane++ {
		bitOffset := lane * bitWidth
		firstByte := bitOffset / 8
		shift := bitOffset % 8
		byteCount := (shift + bitWidth + 7) / 8
		lo, hi, base := &m.lo0, &m.hi0, uint(0)
		if lane >= 4 {
			lo, hi, base = &m.lo1, &m.hi1, g
		}
		for k := uint(0); k < min(byteCount, 4); k++ {
			lo[(lane%4)*4+k] = int8(firstByte + k - base)
		}
		if byteCount == 5 {
			hi[(lane%4)*4+3] = int8(firstByte + 4 - base)
		}
		if lane < 4 {
			m.sr0[lane] = uint32(shift)
			m.sl0[lane] = uint32(8 - shift)
		} else {
			m.sr1[lane-4] = uint32(shift)
			m.sl1[lane-4] = uint32(8 - shift)
		}
	}
	return m
}

func int64Permute(bitWidth uint) unpackInt64Permute {
	var m unpackInt64Permute
	for lane := uint(0); lane < 8; lane++ {
		// At bitWidth 32, lane 7 computes word+1 == 8; VPERMD only uses the
		// low 3 bits of each index so it wraps to word 0, and the bits it
		// contributes are cleared by the 32 bit mask.
		word := (lane * bitWidth) / 32
		shift := (lane * bitWidth) % 32
		if lane < 4 {
			m.perm0[2*lane+0] = uint32(word)
			m.perm0[2*lane+1] = uint32(word + 1)
			m.shift0[lane] = uint64(shift)
		} else {
			m.perm1[2*(lane-4)+0] = uint32(word)
			m.perm1[2*(lane-4)+1] = uint32(word + 1)
			m.shift1[lane-4] = uint64(shift)
		}
	}
	return m
}

func int64WidePermute(bitWidth uint) unpackInt64WidePermute {
	var m unpackInt64WidePermute
	g := (4 * bitWidth) / 8
	for lane := uint(0); lane < 8; lane++ {
		base := uint(0)
		if lane >= 4 {
			base = 8 * g
		}
		rel := lane*bitWidth - base
		word := rel / 32
		shift := rel % 32
		permLo, permHi := &m.permLo0, &m.permHi0
		sr, sl := &m.sr0, &m.sl0
		if lane >= 4 {
			permLo, permHi, sr, sl = &m.permLo1, &m.permHi1, &m.sr1, &m.sl1
		}
		k := lane % 4
		permLo[2*k+0] = uint32(word)
		permLo[2*k+1] = uint32(word+1) & 7
		permHi[2*k+0] = uint32(word+2) & 7
		permHi[2*k+1] = uint32(word+3) & 7
		sr[k] = uint64(shift)
		sl[k] = uint64(64 - shift)
	}
	return m
}

func formatInt8s(v [16]int8) string {
	b := &bytes.Buffer{}
	for i, x := range v {
		if i > 0 {
			fmt.Fprint(b, ", ")
		}
		if x == -128 {
			fmt.Fprint(b, "z")
		} else {
			fmt.Fprintf(b, "%d", x)
		}
	}
	return b.String()
}

func formatUints[T uint32 | uint64](v []T) string {
	b := &bytes.Buffer{}
	for i, x := range v {
		if i > 0 {
			fmt.Fprint(b, ", ")
		}
		fmt.Fprintf(b, "%d", x)
	}
	return b.String()
}

func main() {
	buf := &bytes.Buffer{}
	fmt.Fprintln(buf, "//go:build goexperiment.simd")
	fmt.Fprintln(buf)
	fmt.Fprintln(buf, "// Code generated by gen_unpack_simd_amd64.go. DO NOT EDIT.")
	fmt.Fprintln(buf)
	fmt.Fprintln(buf, "package bitpack")
	fmt.Fprintln(buf)
	fmt.Fprintln(buf, "// z marks a shuffle index whose sign bit is set: VPSHUFB writes zero to")
	fmt.Fprintln(buf, "// the destination byte instead of selecting an input byte.")
	fmt.Fprintln(buf, "const z = -128")
	fmt.Fprintln(buf)

	fmt.Fprintln(buf, "var unpackInt32Shuffles = [32]unpackInt32Shuffle{")
	for bitWidth := uint(1); bitWidth <= 31; bitWidth++ {
		m := int32Shuffle(bitWidth)
		fmt.Fprintf(buf, "\t%d: {\n", bitWidth)
		fmt.Fprintf(buf, "\t\tlo0: [16]int8{%s},\n", formatInt8s(m.lo0))
		fmt.Fprintf(buf, "\t\tlo1: [16]int8{%s},\n", formatInt8s(m.lo1))
		suffix := ""
		if bitWidth < 27 {
			suffix = " // unused: no value spans 5 bytes below 27 bits"
		}
		fmt.Fprintf(buf, "\t\thi0: [16]int8{%s},%s\n", formatInt8s(m.hi0), suffix)
		fmt.Fprintf(buf, "\t\thi1: [16]int8{%s},%s\n", formatInt8s(m.hi1), suffix)
		fmt.Fprintf(buf, "\t\tsr0: [4]uint32{%s}, sr1: [4]uint32{%s},\n", formatUints(m.sr0[:]), formatUints(m.sr1[:]))
		fmt.Fprintf(buf, "\t\tsl0: [4]uint32{%s}, sl1: [4]uint32{%s},\n", formatUints(m.sl0[:]), formatUints(m.sl1[:]))
		fmt.Fprintf(buf, "\t},\n")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)

	fmt.Fprintln(buf, "var unpackInt64Permutes = [33]unpackInt64Permute{")
	for bitWidth := uint(1); bitWidth <= 32; bitWidth++ {
		m := int64Permute(bitWidth)
		fmt.Fprintf(buf, "\t%d: {\n", bitWidth)
		fmt.Fprintf(buf, "\t\tperm0: [8]uint32{%s}, perm1: [8]uint32{%s},\n", formatUints(m.perm0[:]), formatUints(m.perm1[:]))
		fmt.Fprintf(buf, "\t\tshift0: [4]uint64{%s}, shift1: [4]uint64{%s},\n", formatUints(m.shift0[:]), formatUints(m.shift1[:]))
		fmt.Fprintf(buf, "\t},\n")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)

	fmt.Fprintln(buf, "var unpackInt64WidePermutes = [64]unpackInt64WidePermute{")
	for bitWidth := uint(33); bitWidth <= 63; bitWidth++ {
		m := int64WidePermute(bitWidth)
		fmt.Fprintf(buf, "\t%d: {\n", bitWidth)
		fmt.Fprintf(buf, "\t\tpermLo0: [8]uint32{%s}, permHi0: [8]uint32{%s},\n", formatUints(m.permLo0[:]), formatUints(m.permHi0[:]))
		fmt.Fprintf(buf, "\t\tpermLo1: [8]uint32{%s}, permHi1: [8]uint32{%s},\n", formatUints(m.permLo1[:]), formatUints(m.permHi1[:]))
		fmt.Fprintf(buf, "\t\tsr0: [4]uint64{%s}, sl0: [4]uint64{%s},\n", formatUints(m.sr0[:]), formatUints(m.sl0[:]))
		fmt.Fprintf(buf, "\t\tsr1: [4]uint64{%s}, sl1: [4]uint64{%s},\n", formatUints(m.sr1[:]), formatUints(m.sl1[:]))
		fmt.Fprintf(buf, "\t},\n")
	}
	fmt.Fprintln(buf, "}")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile("unpack_simd_tables_amd64.go", src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
