//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
)

var widths = []int{
	2, 3, 4, 5, 6, 7,
	9, 10, 11, 12, 13, 14, 15,
	17, 18, 19, 20, 21, 22, 23,
	25, 26, 27, 28, 29, 30, 31,
}

type integerType struct {
	name        string
	fileName    string
	goType      string
	load        string
	bitwiseAnd  string
	valueStride int
	valueShift  int
}

var integerTypes = []integerType{
	{name: "Int32", fileName: "int32", goType: "int32", load: "MOVL", bitwiseAnd: "ANDL", valueStride: 4, valueShift: 2},
	{name: "Int64", fileName: "int64", goType: "int64", load: "MOVQ", bitwiseAnd: "ANDQ", valueStride: 8, valueShift: 3},
}

func main() {
	for _, integerType := range integerTypes {
		generateGo(integerType)
		generateAssembly(integerType)
	}
}

func generatedWidths(integerType integerType) []int {
	result := append([]int(nil), widths...)
	if integerType.name == "Int32" {
		return append(result, 32)
	}
	for width := 33; width <= 64; width++ {
		result = append(result, width)
	}
	return result
}

func generateGo(integerType integerType) {
	var out bytes.Buffer
	f := &out

	fmt.Fprintln(f, "//go:build !purego")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by gen_pack_amd64.go; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package bitpack")
	fmt.Fprintln(f)
	for _, width := range generatedWidths(integerType) {
		fmt.Fprintln(f, "//go:noescape")
		fmt.Fprintf(f, "func pack%sx%dbitsAMD64(dst []byte, src []%s)\n\n", integerType.name, width, integerType.goType)
	}
	fmt.Fprintf(f, "func pack%sGeneratedAMD64(dst []byte, src []%s, bitWidth uint) {\n", integerType.name, integerType.goType)
	fmt.Fprintln(f, "\tswitch bitWidth {")
	for _, width := range generatedWidths(integerType) {
		fmt.Fprintf(f, "\tcase %d:\n\t\tpack%sx%dbitsAMD64(dst, src)\n", width, integerType.name, width)
	}
	fmt.Fprintln(f, "\t}")
	fmt.Fprintln(f, "}")

	fileName := fmt.Sprintf("pack_%s_generated_amd64.go", integerType.fileName)
	if err := os.WriteFile(fileName, out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func generateAssembly(integerType integerType) {
	var out bytes.Buffer
	f := &out

	fmt.Fprintln(f, "//go:build !purego")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by gen_pack_amd64.go; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "#include \"textflag.h\"")
	for _, width := range generatedWidths(integerType) {
		fmt.Fprintln(f)
		emitKernel(f, integerType, width)
	}

	fileName := fmt.Sprintf("pack_%s_generated_amd64.s", integerType.fileName)
	if err := os.WriteFile(fileName, out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func emitKernel(f io.Writer, integerType integerType, width int) {
	fmt.Fprintf(f, "// func pack%sx%dbitsAMD64(dst []byte, src []%s)\n", integerType.name, width, integerType.goType)
	fmt.Fprintf(f, "TEXT ·pack%sx%dbitsAMD64(SB), NOSPLIT, $0-48\n", integerType.name, width)
	fmt.Fprintln(f, "\tMOVQ dst_base+0(FP), AX")
	fmt.Fprintln(f, "\tMOVQ src_base+24(FP), BX")
	fmt.Fprintln(f, "\tMOVQ src_len+32(FP), DX")
	fmt.Fprintf(f, "\tSHLQ $%d, DX\n", integerType.valueShift)
	fmt.Fprintln(f, "\tADDQ BX, DX")
	if width > 32 && width < 64 {
		fmt.Fprintf(f, "\tMOVQ $0x%x, R10\n", uint64(1)<<width-1)
	}
	fmt.Fprintf(f, "pack_%s_%dbit_amd64_loop:\n", integerType.fileName, width)

	switch {
	case width == integerType.valueStride*8:
		emitCopyKernel(f, integerType)
	case width <= 7:
		emitSmallKernel(f, integerType, width)
	case width <= 15:
		emitMediumKernel(f, integerType, width)
	case width <= 21:
		emitLargeKernel(f, integerType, width)
	case width <= 31:
		emitPairKernel(f, integerType, width)
	default:
		emitWideKernel(f, integerType, width)
	}

	fmt.Fprintf(f, "\tADDQ $%d, BX\n", 8*integerType.valueStride)
	fmt.Fprintf(f, "\tADDQ $%d, AX\n", width)
	fmt.Fprintln(f, "\tCMPQ BX, DX")
	fmt.Fprintf(f, "\tJB pack_%s_%dbit_amd64_loop\n", integerType.fileName, width)
	fmt.Fprintln(f, "\tRET")
}

func emitCopyKernel(f io.Writer, integerType integerType) {
	for offset := 0; offset < 8*integerType.valueStride; offset += 16 {
		reg := fmt.Sprintf("X%d", offset/16)
		fmt.Fprintf(f, "\tMOVOU %d(BX), %s\n", offset, reg)
	}
	for offset := 0; offset < 8*integerType.valueStride; offset += 16 {
		reg := fmt.Sprintf("X%d", offset/16)
		fmt.Fprintf(f, "\tMOVOU %s, %d(AX)\n", reg, offset)
	}
}

func emitWideKernel(f io.Writer, integerType integerType, width int) {
	wordCount := (width + 7) / 8
	for word := 0; word < wordCount; word++ {
		wordOffset := word * 64
		firstValue := wordOffset / width
		lastValue := min(7, (wordOffset+63)/width)
		for value := firstValue; value <= lastValue; value++ {
			reg := "R9"
			if value == firstValue {
				reg = "R8"
			}
			fmt.Fprintf(f, "\t%s %d(BX), %s\n", integerType.load, value*integerType.valueStride, reg)
			fmt.Fprintln(f, "\tANDQ R10, "+reg)
			shift := value*width - wordOffset
			switch {
			case shift > 0:
				fmt.Fprintf(f, "\tSHLQ $%d, %s\n", shift, reg)
			case shift < 0:
				fmt.Fprintf(f, "\tSHRQ $%d, %s\n", -shift, reg)
			}
			if value != firstValue {
				fmt.Fprintln(f, "\tORQ R9, R8")
			}
		}

		offset := word * 8
		if word < width/8 {
			fmt.Fprintf(f, "\tMOVQ R8, %d(AX)\n", offset)
		} else {
			emitTailStore(f, "R8", offset, width%8)
		}
	}
}

func emitSmallKernel(f io.Writer, integerType integerType, width int) {
	regs := []string{"R8", "R9", "R10", "R11", "R12", "R13", "R14", "R15"}
	for i, reg := range regs {
		emitValue(f, integerType, reg, i, i*width, width)
	}
	for stride := 1; stride < len(regs); stride *= 2 {
		for i := 0; i < len(regs); i += 2 * stride {
			fmt.Fprintf(f, "\tORQ %s, %s\n", regs[i+stride], regs[i])
		}
	}
	emitTailStore(f, regs[0], 0, width)
}

func emitMediumKernel(f io.Writer, integerType integerType, width int) {
	low := []string{"R8", "R9", "R10", "R11"}
	high := []string{"R12", "R13", "R14", "R15"}
	for i, reg := range low {
		emitValue(f, integerType, reg, i, i*width, width)
	}
	for i, reg := range high {
		emitValue(f, integerType, reg, i+4, i*width, width)
	}
	emitFourValueReduction(f, low)
	emitFourValueReduction(f, high)

	shift := 4 * width
	fmt.Fprintln(f, "\tMOVQ R12, R9")
	fmt.Fprintf(f, "\tSHLQ $%d, R9\n", shift)
	fmt.Fprintln(f, "\tORQ R9, R8")
	fmt.Fprintf(f, "\tSHRQ $%d, R12\n", 64-shift)
	fmt.Fprintln(f, "\tMOVQ R8, (AX)")
	emitTailStore(f, "R12", 8, width-8)
}

func emitLargeKernel(f io.Writer, integerType integerType, width int) {
	groups := [][]string{
		{"R8", "R9", "R10"},
		{"R11", "R12", "R13"},
		{"R14", "R15"},
	}
	value := 0
	for _, group := range groups {
		for i, reg := range group {
			emitValue(f, integerType, reg, value, i*width, width)
			value++
		}
		for i := 1; i < len(group); i++ {
			fmt.Fprintf(f, "\tORQ %s, %s\n", group[i], group[0])
		}
	}

	groupBits := 3 * width
	thirdOffset := 6*width - 64
	fmt.Fprintln(f, "\tMOVQ R11, R9")
	fmt.Fprintf(f, "\tSHLQ $%d, R9\n", groupBits)
	fmt.Fprintln(f, "\tORQ R9, R8")
	fmt.Fprintf(f, "\tSHRQ $%d, R11\n", 64-groupBits)
	fmt.Fprintln(f, "\tMOVQ R14, R15")
	fmt.Fprintf(f, "\tSHLQ $%d, R15\n", thirdOffset)
	fmt.Fprintln(f, "\tORQ R15, R11")
	fmt.Fprintf(f, "\tSHRQ $%d, R14\n", 64-thirdOffset)
	fmt.Fprintln(f, "\tMOVQ R8, (AX)")
	fmt.Fprintln(f, "\tMOVQ R11, 8(AX)")
	emitTailStore(f, "R14", 16, width-16)
}

func emitPairKernel(f io.Writer, integerType integerType, width int) {
	pairs := [][2]string{
		{"R8", "R9"},
		{"R10", "R11"},
		{"R12", "R13"},
		{"R14", "R15"},
	}
	for i, pair := range pairs {
		emitValue(f, integerType, pair[0], 2*i, 0, width)
		emitValue(f, integerType, pair[1], 2*i+1, width, width)
		fmt.Fprintf(f, "\tORQ %s, %s\n", pair[1], pair[0])
	}

	pairBits := 2 * width
	fmt.Fprintln(f, "\tMOVQ R10, R9")
	fmt.Fprintf(f, "\tSHLQ $%d, R9\n", pairBits)
	fmt.Fprintln(f, "\tORQ R9, R8")
	fmt.Fprintln(f, "\tMOVQ R10, R11")
	fmt.Fprintf(f, "\tSHRQ $%d, R11\n", 64-pairBits)
	fmt.Fprintln(f, "\tMOVQ R12, R13")
	fmt.Fprintf(f, "\tSHLQ $%d, R13\n", 2*pairBits-64)
	fmt.Fprintln(f, "\tORQ R13, R11")
	fmt.Fprintf(f, "\tSHRQ $%d, R12\n", 128-2*pairBits)
	fmt.Fprintln(f, "\tMOVQ R14, R15")
	fmt.Fprintf(f, "\tSHLQ $%d, R15\n", 3*pairBits-128)
	fmt.Fprintln(f, "\tORQ R15, R12")

	fmt.Fprintln(f, "\tMOVQ R8, (AX)")
	fmt.Fprintln(f, "\tMOVQ R11, 8(AX)")
	if width <= 23 {
		emitTailStore(f, "R12", 16, width-16)
		return
	}
	fmt.Fprintf(f, "\tSHRQ $%d, R14\n", 192-3*pairBits)
	fmt.Fprintln(f, "\tMOVQ R12, 16(AX)")
	emitTailStore(f, "R14", 24, width-24)
}

func emitValue(f io.Writer, integerType integerType, reg string, index, shift, width int) {
	fmt.Fprintf(f, "\t%s %d(BX), %s\n", integerType.load, index*integerType.valueStride, reg)
	fmt.Fprintf(f, "\t%s $0x%x, %s\n", integerType.bitwiseAnd, (1<<width)-1, reg)
	if shift != 0 {
		fmt.Fprintf(f, "\tSHLQ $%d, %s\n", shift, reg)
	}
}

func emitFourValueReduction(f io.Writer, regs []string) {
	fmt.Fprintf(f, "\tORQ %s, %s\n", regs[1], regs[0])
	fmt.Fprintf(f, "\tORQ %s, %s\n", regs[3], regs[2])
	fmt.Fprintf(f, "\tORQ %s, %s\n", regs[2], regs[0])
}

func emitTailStore(f io.Writer, reg string, offset, byteCount int) {
	if byteCount >= 4 {
		fmt.Fprintf(f, "\tMOVL %s, %d(AX)\n", reg, offset)
		offset += 4
		byteCount -= 4
		if byteCount > 0 {
			fmt.Fprintf(f, "\tSHRQ $32, %s\n", reg)
		}
	}
	if byteCount >= 2 {
		fmt.Fprintf(f, "\tMOVW %s, %d(AX)\n", reg, offset)
		offset += 2
		byteCount -= 2
		if byteCount > 0 {
			fmt.Fprintf(f, "\tSHRQ $16, %s\n", reg)
		}
	}
	if byteCount == 1 {
		fmt.Fprintf(f, "\tMOVB %s, %d(AX)\n", reg, offset)
	}
}
